#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Dietphone.Resource", IsApplication=true)]

namespace Dietphone
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxBind = global::Dietphone.Resource.Attribute.MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxDropDownItemTemplate = global::Dietphone.Resource.Attribute.MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxGroupItemTemplate = global::Dietphone.Resource.Attribute.MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxItemTemplate = global::Dietphone.Resource.Attribute.MvxItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxLang = global::Dietphone.Resource.Attribute.MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxSource = global::Dietphone.Resource.Attribute.MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxTemplate = global::Dietphone.Resource.Attribute.MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Id.MvvmCrossTagId = global::Dietphone.Resource.Id.MvvmCrossTagId;
			global::MvvmCross.Binding.Droid.Resource.Id.MvxBindingTagUnique = global::Dietphone.Resource.Id.MvxBindingTagUnique;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding = global::Dietphone.Resource.Styleable.MvxBinding;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxBind = global::Dietphone.Resource.Styleable.MvxBinding_MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxLang = global::Dietphone.Resource.Styleable.MvxBinding_MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl = global::Dietphone.Resource.Styleable.MvxControl;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl_MvxTemplate = global::Dietphone.Resource.Styleable.MvxControl_MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView = global::Dietphone.Resource.Styleable.MvxExpandableListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::Dietphone.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView = global::Dietphone.Resource.Styleable.MvxImageView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView_MvxSource = global::Dietphone.Resource.Styleable.MvxImageView_MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView = global::Dietphone.Resource.Styleable.MvxListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::Dietphone.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxItemTemplate = global::Dietphone.Resource.Styleable.MvxListView_MvxItemTemplate;
			global::Xamarin.InAppBilling.Resource.String.library_name = global::Dietphone.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010004
			public const int MvxDropDownItemTemplate = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int MvxGroupItemTemplate = 2130771973;
			
			// aapt resource value: 0x7f010003
			public const int MvxItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int MvxLang = 2130771969;
			
			// aapt resource value: 0x7f010006
			public const int MvxSource = 2130771974;
			
			// aapt resource value: 0x7f010002
			public const int MvxTemplate = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060004
			public const int accent_material_dark = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int extreme_background = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int extreme_foreground = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int material_deep_teal_200 = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int material_grey_600 = 2131099649;
			
			// aapt resource value: 0x7f060005
			public const int primary_dark_material_light = 2131099653;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070000
			public const int extra_large = 2131165184;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_add = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_alternatives = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_cancel = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_changelog = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_check = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_delete = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_insulin = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_lock = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_lock_open = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_meal = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_more = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_save = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_search = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_sugar = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int Icon = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int splash = 2130837519;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050008
			public const int ListView = 2131034120;
			
			// aapt resource value: 0x7f050000
			public const int MvvmCrossTagId = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int MvxBindingTagUnique = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int about_link = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int about_link_email = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int browser = 2131034117;
			
			// aapt resource value: 0x7f050009
			public const int embeddedaboutview_changelog = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int exportandimportview_exporttocloudnow = 2131034122;
			
			// aapt resource value: 0x7f05000c
			public const int insulineditingview_cancel = 2131034124;
			
			// aapt resource value: 0x7f05000e
			public const int insulineditingview_copy = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int insulineditingview_delete = 2131034127;
			
			// aapt resource value: 0x7f05000b
			public const int insulineditingview_meal = 2131034123;
			
			// aapt resource value: 0x7f05000d
			public const int insulineditingview_save = 2131034125;
			
			// aapt resource value: 0x7f050004
			public const int license_text = 2131034116;
			
			// aapt resource value: 0x7f050017
			public const int mainview_about = 2131034135;
			
			// aapt resource value: 0x7f050013
			public const int mainview_add = 2131034131;
			
			// aapt resource value: 0x7f050015
			public const int mainview_exportandimportdata = 2131034133;
			
			// aapt resource value: 0x7f050012
			public const int mainview_insulin = 2131034130;
			
			// aapt resource value: 0x7f050010
			public const int mainview_meal = 2131034128;
			
			// aapt resource value: 0x7f050014
			public const int mainview_search = 2131034132;
			
			// aapt resource value: 0x7f050016
			public const int mainview_settings = 2131034134;
			
			// aapt resource value: 0x7f050011
			public const int mainview_sugar = 2131034129;
			
			// aapt resource value: 0x7f050018
			public const int mainview_welcomescreen = 2131034136;
			
			// aapt resource value: 0x7f05001a
			public const int mealeditingview_cancel = 2131034138;
			
			// aapt resource value: 0x7f05001c
			public const int mealeditingview_delete = 2131034140;
			
			// aapt resource value: 0x7f050019
			public const int mealeditingview_insulin = 2131034137;
			
			// aapt resource value: 0x7f05001b
			public const int mealeditingview_save = 2131034139;
			
			// aapt resource value: 0x7f05001d
			public const int producteditingview_cancel = 2131034141;
			
			// aapt resource value: 0x7f05001f
			public const int producteditingview_delete = 2131034143;
			
			// aapt resource value: 0x7f05001e
			public const int producteditingview_save = 2131034142;
			
			// aapt resource value: 0x7f050007
			public const int sugar_chart = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int suggested_insulin_header = 2131034118;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CalculationDetails = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CalculationDetailsAlternatives = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int DateTimeLock_Include = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int EmbeddedAboutView = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ExportAndImportView = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int InlineViewIcons_Include = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int InsulinEditingView = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Journal_Item = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int JournalView = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Listing_Group = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Listing_Include = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int ListingView = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int MainView = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int Meal_Item = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int MealEditingView = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int MealItemEditing = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int Pattern = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int Pattern_Sugar = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int ProductEditingView = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int ProductListing_Item = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int Replacement_Item = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int Scores = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int SettingsView = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int SplashScreen = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int SugarEditing = 2130903064;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f090000
			public const int embeddedaboutview_menu = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int exportandimportview_menu = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int insulineditingview_menu = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int mainview_menu = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int mealeditingview_menu = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int producteditingview_menu = 2131296261;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int Theme_Splash = 2131230720;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771970};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxExpandableListView = new int[] {
					2130771973};
			
			// aapt resource value: 0
			public const int MvxExpandableListView_MvxGroupItemTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771974};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771971,
					2130771972};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
